language: node_js

node_js:
  - '8'

script:
  - npm run build

addons:
  ssh_known_hosts: 134.175.177.132

before_deploy:
  - openssl aes-256-cbc -K $encrypted_e275131d40d4_key -iv $encrypted_e275131d40d4_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public xcatliu@134.175.177.132:/home/xcatliu/test
  on:
    branch: master